{% set package_name = "btms-ui" %}
{% set import_name = "btms-ui" %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv



requirements:
  build:
  - python >=3.7
  - setuptools_scm
  - pip
  run:
  - python >=3.7
  - pcdsdevices
  - qtpy
  - pyqt <5.15



test:
  imports:
  - btms_ui
  requires:
  - pytest



about:
  home: https://github.com/pcdshub/btms_ui
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  summary: Beam Transport System Motion User Interface
